// Generated by CoffeeScript 1.10.0
var config, prompt, startup;

prompt = require('prompt-sync');

startup = require('user-startup');

config = require('config');

startup.create("dyndns-" + config.id, '/usr/local/bin/npm', ['start']);
